### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by ajhodges** [hackgvl/trolley-tracker-web#2]
The map isn't rendering on http://trackthetrolley.com/greenville-sc-trolley/

It looks like there is a JS error related to loading routes... don't have time to dig deeper at the moment

**Comment by bikeoid** [comment]
What references this URL?   The root folder works for me at http://trackthetrolley.com/

**Comment by jeremywight** [comment]
We should fix that, yeahthattrolley.com points there

**Comment by bikeoid** [comment]
Is this best fixed at the redirect (GoDaddy?) , or should this be changed on the web site ( unique display at http://trackthetrolley.com/greenville-sc-trolley/ , such as map only without borders) ?

**Comment by Linktheoriginal** [comment]
I'm not seeing an error.  Is this only under certain conditions?

That iframe looks like it's still coming from my site - were we going to move it to the main host?

**Comment by ajhodges** [comment]
Looks like it magically started working again, I don't know what changed.. could possibly just be under certain conditions (maybe only when there is an active route?)

**Comment by bikeoid** [comment]
We moved trackthetrolley.com to the main host.   This one slipped through the cracks.   I should trace down to see where the redirect happens and add another redirect if necessary.

**Comment by bikeoid** [comment]
I can add a redirect to end at the right place but there are already a bunch of redirects to get where it does today.   It should be edited at GoDaddy for fastest response.

**Comment by jeremywight** [comment]
I can update the redirect on GoDaddy if we think that will solve the issue.
I had originally thought the separate domains would be helpful for
marketing/tracking, however given that the website has fewer active users
than the mobile apps, perhaps just directing to trackthetrolley.com would
be fine. Let me know what y'all think.

**Comment by bikeoid** [comment]
I would say to update on GoDaddy.   We can rearrange it if necessary if there are some long term marketing campaigns.

**Comment by jeremywight** [comment]
yeahthattrolley.com is now set to redirect to trackthetrolley.com

**Comment by agautsc** [comment]
@jeremywight are you paying hosting for the marketing site? If so, it might be worth using GitHub pages https://pages.github.com/ It's free and now it even provides an SSL cert.

**Comment by jeremywight** [comment]
Hey Adam! Yes, though it's on my shared virtual server so it doesn't really
cost me anything, but that's an interesting thought at least as it allows
it to be more "Open" perhaps

**Comment by agautsc** [comment]
Good point. It would be easier for others to help make changes and improvements for sure. If you want to do it and need any help -- let me know.

**Comment by invisionjeremy** [comment]
Resolved
