### ISSUE TITLE
SSL Cert is expired

### ISSUE THREAD

**Issue by jeremywight** [hackgvl/trolley-tracker-web#3]
In checking a few things I found that the SSL cert is expired. I'm renewing with LetsEncrypt that and once I have confirmed it's working will close this issue.

**Comment by jeremywight** [comment]
So I re-enabled the SSL cert and was about to enable an .htaccess rewrite to force all http traffic to redirect to https, however api.yeahthattrolley.com doesn't have SSL so I can't enable that. 

@bikeoid probably not the biggest of concerns considering the coming Azure server changes, but perhaps when we do the change we can set up a LetsEncrypt cert and then force SSL. For now I'm closing out this issue since the SSL cert is now active.

**Comment by bikeoid** [comment]
Adding SSL is a priority wish list for me for api.yeahthattrolley.com.  But when I checked a year ago, Azure did not have an "Add LetsEncrypt" button.   At the time Microsoft still sold certificates with an "Enable SSL and charge my account" button so I suppose they didn't want to cannibalize that business.  You could still add LetsEncrypt yourself, but you had to manually move request, auth, and certificate files manually in and out via the LetsEncrypt API.

**Comment by bikeoid** [comment]
And checking back on Azure - I see that someone has written a plugin to lessen the pain, but it's still requires some manual attention.   The all time highest voted requested feature for years running now, but still no clean feature in sight.  https://feedback.azure.com/forums/169385-web-apps/suggestions/36950533-add-support-for-free-tls-ssl-certificates

**Comment by jeremywight** [comment]
Oh, wow. Yeah I just assumed that they could accept the free certs
